title = "永宮 悠大"
baseURL = "https://ngmy.github.io/"
theme = "hugo-resume"
languageCode = "ja-JP"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true
defaultContentLanguage = "ja"

[params]
address = ""
email = "y.nagamiya+work@gmail.com"
favicon = "/favicon.ico"
firstName = "Yuta"
lastName = "Nagamiya"
phone = "09057595237"
profileImage = "img/profile.png"
showQr = false
showContact = true
showCertifications = true
showSocializations = true
sections = [
  "skills",
  "creations",
  "experience",
  "education",
  "resume",
]
gitCommitPrefix = "https://github.com/ngmy/ngmy.github.io/commit/"
firstNameJa = "悠大"
lastNameJa = "永宮"
firstNameKana = "ユウタ"
lastNameKana = "ナガミヤ"
description = "永宮悠大のポートフォリオサイトです。"

[params.google]

[params.google.analytics]
trackerID = "G-20TT5CYF3T"

[[params.handles]]
link = "https://github.com/ngmy"
name = "GitHub"

[[params.handles]]
link = "https://qiita.com/ngmy"
name = "Qiita"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
