title = "ngmy.github.io"
baseURL = "https://ngmy.github.io"
languageCode = "ja"
theme = "ananke"

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-20TT5CYF3T"
enableRobotsTXT = true

[languages]
  [languages.ja]
    title = "ngmy.github.io"
    weight = 1
    contentDir = "content/ja"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  site_logo = ""
  description = "ngmy（永宮 悠大）のホームページ。"
  facebook = ""
  twitter = "https://twitter.com/ngmy"
  instagram = "https://instagram.com/ngmy"
  youtube = ""
  github = "https://github.com/ngmy"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  qiita = "https://qiita.com/ngmy"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/cover.jpg"
  recent_posts_number = 2
  custom_css = ["css/custom.css"]
  cover_dimming_class = "bg-black-40"
  body_classes = "noto-sans-jp bg-near-white"
